Repository GmBodhi/shandler, pull requests merged in 2021-07, with the labels that each got.

#27 fix(RegExp error): Fixed the error
  js/index.js
Labels: bug

#28 Fixing interaction.defer
  js/interaction.js
Labels: Fixed

#29 Updating Documentation
  getting-started/basic-usage.md
  getting-started/buttons/README.md
  getting-started/commands.md
  getting-started/methods.md
  getting-started/shclient-and-interaction.md
Labels: documentation

#32 Updating Documentation
  README.md
  SUMMARY.md
  buttons/button-dropdowns.md
  buttons/buttonclick-event.md
  buttons/buttons-documentation.md
  buttons/getting-started-with-buttons.md
  getting-started/basic-usage.md
  getting-started/buttons/README.md
  getting-started/deleting-commands.md
  getting-started/methods.md
  getting-started/shclient-and-interaction.md
  interactions/methods.md
Labels: Fixed, documentation, enhancement

#33 Updating Documentation
  buttons/button-dropdowns.md
  buttons/buttonclick-event.md
  buttons/getting-started-with-buttons.md
  interactions/methods.md
Labels: documentation, enhancement
